"""Generate survey/sources.js from the archive's metadata.json files.

Run from the repository root:  python3 survey/build_sources.py
"""
import glob
import json
import os
import re
import html

BLOB = "https://github.com/JDLu2003/ASSA/blob/claude/jolly-hamilton-pz9s9e/"


def pick(d, *names):
    for n in names:
        if os.path.exists(os.path.join(d, n)):
            return BLOB + os.path.join(d, n)
    return None


out = []
for f in sorted(glob.glob("sources/official/*/*/*/metadata.json")):
    d = os.path.dirname(f)
    m = json.load(open(f))
    it = m.get("item", {})
    vendor, product, page = d.split("/")[2:5]
    out.append({
        "id": f"{vendor}/{product}/{page}",
        "kind": "official",
        "vendor": vendor,
        "product": product,
        "title": m.get("title") or it.get("url"),
        "url": m.get("final_url") or it.get("url"),
        "pdf": pick(d, "page.complete.pdf", "page.pdf"),
        "txt": pick(d, "page.txt"),
        "captured": (m.get("capture_started_at") or "")[:10],
    })
for f in sorted(glob.glob("sources/papers/*/*/metadata.json")):
    d = os.path.dirname(f)
    m = json.load(open(f))
    it = m.get("item", {})
    topic, pid = d.split("/")[2:4]
    title = it.get("title") or m.get("title")
    authors = it.get("authors", [])
    landing = os.path.join(d, "landing.html")
    if (not title or not authors) and os.path.exists(landing):
        page = open(landing, errors="ignore").read()
        t = re.search(r'name="citation_title" content="(.*?)"', page)
        if t and not title:
            title = html.unescape(t.group(1))
        if not authors:
            authors = [html.unescape(a) for a in re.findall(r'name="citation_author" content="(.*?)"', page)]
    venue = it.get("venue") or (("arXiv " + it["arxiv"]) if it.get("arxiv") else "")
    out.append({
        "id": pid,
        "kind": "paper",
        "topic": topic,
        "title": title or pid,
        "authors": authors[:4],
        "venue": venue,
        "date": (it.get("published") or "")[:10],
        "url": it.get("landing_url") or m.get("requested_url"),
        "pdf": pick(d, "paper.pdf"),
        "txt": pick(d, "paper.txt"),
    })

with open("survey/sources.js", "w") as fh:
    fh.write("// Generated by survey/build_sources.py from sources/**/metadata.json\n")
    fh.write("window.SOURCES = ")
    json.dump(out, fh, ensure_ascii=False, indent=0)
    fh.write(";\n")
print(len(out), "sources")
